# Publish to Quay.io
publish:
  # Unstable
  docker:
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: urbit/drone-kubernetes-helm
    tag:
    - latest
    - $$COMMIT
    when:
      event: push
      branch: master
  # RC + Stable
  docker:
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: urbit/drone-kubernetes-helm
    tag:
    - $$TAG
    - $$COMMIT
    when:
      event: tag
      branch: refs/tags/*
