build:
  image: alpine:3.8
  environment:
    - KUBE_CONFIG=$$KUBE_CONFIG
    - KUBE_CA=$$KUBE_CA
    - KUBE_CLIENT_CERT=$$KUBE_CLIENT_CERT
    - KUBE_CLIENT_KEY=$$KUBE_CLIENT_KEY
  commands:
    - apk add --no-cache curl
    - "sed -i -e '
        s/{{KUBE_CONFIG}}/'\"$KUBE_CONFIG\"'/g;
        s/{{KUBE_CA}}/'\"$KUBE_CA\"'/g;
        s/{{KUBE_CLIENT_CERT}}/'\"$KUBE_CLIENT_CERT\"'/g;
        s/{{KUBE_CLIENT_KEY}}/'\"$KUBE_CLIENT_KEY\"'/g;
      ' ./test-drone-config.json"
    - curl https://get.docker.io/builds/Linux/x86_64/docker-latest -o /usr/local/bin/docker
    - chmod +x /usr/local/bin/docker 
    - docker -H unix:///var/run/docker.sock build --no-cache . -t test
    - docker run -i test < test-drone-config.json

# Publish to Quay.io
publish:
  # Unstable
  docker:
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: urbit/drone-kubernetes-helm
    tag:
    - latest
    - $$COMMIT
    when:
      event: push
      branch: master
  # RC + Stable
  docker:
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: urbit/drone-kubernetes-helm
    tag:
    - $$TAG
    - $$COMMIT
    when:
      event: tag
      branch: refs/tags/*
