pipeline:
  build:
    image: python:3.6-alpine
    commands:
    - pip install -r requirements.txt
    - pytest

  publish:
    image: plugins/docker
    repo: mandrean/hello-world
    tag:
    - latest
    - ${DRONE_COMMIT}

  deploy:
    image: mandrean/drone-kubernetes-helm:v0.3.0-k8s-v1.6-4-helm-v2.4.2
    kube-config:
      # the clusters
      clusters:
      - name: aws-1
        cluster:
          certificate-authority: /home/credentials/ca.pem
          server: https://kube-aws.evil-corp.io
      - name: gcp-1
        cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBasdsasdasd
          server: https://kube-gcp-1.evil-corp.io
      - name: gcp-2
        cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBasdsasdasd
          server: https://kube-gcp-2.evil-corp.io
      # the users
      users:
      - name: aws-1-admin
        user:
          client-certificate: /home/credentials/aws-admin.pem
          client-key: /home/credentials/aws-admin-key.pem
      - name: gcp-1-admin
        user:
          client-certificate-data: LS0tLS1CRUdJTiBasdsasdasd
          client-key-data: LS0tLS1CRUdJTiBasdsasdasd
          password: abcd123
          username: admin
      - name: gcp-2-admin
        user:
          auth-provider:
            config:
              access-token: ya29.asdasdasd
              expiry: 2017-05-21 13:33:37.145094
            name: gcp
      # the contexts that pairs clusters & users together
      contexts:
      - name: aws-1
        context:
          cluster: aws-1
          user: aws-1-admin
      - name: gcp-1
        context:
          cluster: gcp-1
          user: gcp-1-admin
      - name: gcp-2
        context:
          cluster: gcp-2
          user: gcp-2-admin
      current-context: gcp-1
    helm-commands:
    - install:
        chart: nginx
        release: dev-nginx
        flags:
        - dry-run: true
        - kube-context: gcp-1
    - get:
        subcommand: values
        release: dev-nginx
        flags:
        - all: true
        - kube-context: gcp-1
        - output: ./values-dev.yaml
    - upgrade:
        chart: nginx
        release: dev-nginx
        flags:
        - namespace: default
        - values: ./values-dev.yaml
        - kube-context: gcp-1
        - set: imageTag=1.10-alpine
